# -*- coding: utf-8 -*-
"""Data_science_cheick_moctar_traore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lGpyuNxHFzA6H0LKEumIvPHs1qqgfhJ6

# ============================================================
#
#        MACHINE LEARNING — COMPARATIVE PROJECT
#
#  Project Title : Player Position Classification Using
#                  Decision Tree and Random Forest
#                  on the FIFA 22 Dataset
#
# ----------------------------------------------------------------
#
#  Student Name  : Cheick Moctar Traore
#  Student ID    : 2592106
#
#
# ----------------------------------------------------------------
#
##  Description:
####  This project compares two machine learning algorithms —Decision Tree and Random Forest — on the task ofpredicting player positions (DEF, MID, FWD, GK) using  the FIFA 22 complete player dataset from Kaggle.The project includes baseline models, systematichyperparameter tuning using GridSearchCV, and a full comparative analysis of results.
#
# ============================================================

##  IMPORT LIBRARIES
#### We import all the tools we need:
#### - pandas: to load and manipulate the dataset
#### - numpy: for numerical operations
#### - matplotlib & seaborn: to create visualizations
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## MOUNT GOOGLE DRIVE & LOAD DATASET
#### We connect to Google Drive where our file is stored,
#### then load players_22.csv into a pandas DataFrame.
#### low_memory=False avoids dtype warnings on large files.

"""

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/fifa22/players_22.csv', low_memory=False)
print(df.shape)
print(df.head())

"""## CHECK MISSING VALUES
### Before using any column as a feature, we need to know
### which columns have missing data and how much.
### We calculate the percentage of missing values per column.

"""

missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100
print(missing_pct[missing_pct > 0].sort_values(ascending=False))

"""##EXPLORE THE POSITION COLUMN
### The player_positions column is our target variable.
### We print the most common values to understand
### what the raw position data looks like before cleaning.
"""

print(df['player_positions'].value_counts().head(20))

"""##VISUALIZE POSITION DISTRIBUTION
### We plot the top 15 most common positions as a bar chart to visually understand how players are distributed across different positions in the dataset.

"""

df['player_positions'].value_counts().head(15).plot(kind='bar', figsize=(12,5))
plt.title('Top 15 Player Positions in FIFA 22')
plt.xlabel('Position')
plt.ylabel('Count')
plt.tight_layout()
plt.show()

"""### STEP 6: EXTRACT FIRST POSITION
### Players can have multiple positions listed (e.g. "CM, CAM"). We only keep the first position listed for each player, since that represents their primary role on the field.

"""

df['primary_position'] = df['player_positions'].apply(lambda x: x.split(',')[0].strip())
print(df['primary_position'].value_counts())

"""### STEP 7: MAP POSITIONS TO 4 CLEAN CLASSES
### We group all specific positions into 4 broad categories:
### - GK  → Goalkeeper
### - DEF → Defenders (CB, RB, LB, RWB, LWB)
### - MID → Midfielders (CM, CAM, CDM, RM, LM)
### - FWD → Forwards (ST, CF, LW, RW)
### Any unrecognized position is marked as NaN and dropped.

"""

position_map = {
    'GK': 'GK',
    'CB': 'DEF', 'RB': 'DEF', 'LB': 'DEF', 'RWB': 'DEF', 'LWB': 'DEF',
    'CDM': 'DEF',
    'CM': 'MID', 'CAM': 'MID', 'RM': 'MID', 'LM': 'MID',
    'ST': 'FWD', 'CF': 'FWD', 'LW': 'FWD', 'RW': 'FWD'
}

df['position_class'] = df['primary_position'].map(position_map)

# Check how many got mapped vs unmapped
print(df['position_class'].value_counts())
print("\nUnmapped positions:")
print(df[df['position_class'].isna()]['primary_position'].value_counts())

"""## SELECT FEATURES
### We use the 6 main skill ratings as our input features. These are: pace, shooting, passing, dribbling, defending, and physic. We drop rows where any of these values are missing.

"""

features = ['pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic']

# Keep only rows where all features AND position_class are present
df_clean = df[features + ['position_class']].dropna()

print(f"Dataset shape after cleaning: {df_clean.shape}")
print(f"\nFinal class distribution:")
print(df_clean['position_class'].value_counts())

"""## VISUALIZE FINAL CLASS DISTRIBUTION
### After cleaning, we check how balanced our 4 classes are. A balanced dataset means each class has a similar number of players — important for fair model evaluation.

"""

df_clean['position_class'].value_counts().plot(kind='bar', color=['steelblue','salmon','green','orange'], figsize=(8,5))
plt.title('Final Position Class Distribution')
plt.xlabel('Position Class')
plt.ylabel('Number of Players')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

"""## (REVISED): HANDLE MISSING VALUES FOR GOALKEEPERS
### GKs have missing outfield stats (pace, shooting, etc.) because they don't use those skills in the game. We fill those missing values with 0 for GK players only. Then we re-clean the dataset keeping all 4 classes.

"""

# Fill missing outfield stats with 0 for GKs
outfield_features = ['pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic']

for feature in outfield_features:
    df.loc[df['position_class'] == 'GK', feature] = df.loc[df['position_class'] == 'GK', feature].fillna(0)

# Now rebuild the clean dataset
df_clean = df[outfield_features + ['position_class']].dropna()

print(f"Dataset shape after cleaning: {df_clean.shape}")
print(f"\nFinal class distribution:")
print(df_clean['position_class'].value_counts())

"""### STEP 9 (REVISED): VISUALIZE FINAL CLASS DISTRIBUTION
### Now we should see all 4 classes including GK.

"""

df_clean['position_class'].value_counts().plot(
    kind='bar',
    color=['steelblue', 'salmon', 'green', 'orange'],
    figsize=(8,5)
)
plt.title('Final Position Class Distribution (4 Classes)')
plt.xlabel('Position Class')
plt.ylabel('Number of Players')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

"""## DEFINE FEATURES (X) AND TARGET (y)
### X contains the 6 input features the model will learn from. y contains the target variable we want to predict. Think of X as the questions and y as the answers.

"""

X = df_clean[['pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic']]
y = df_clean['position_class']

print(f"Features shape: {X.shape}")
print(f"Target shape: {y.shape}")
print(f"\nFeature preview:")
print(X.head())

"""## TRAIN/TEST SPLIT
### We split the data into 80% training and 20% testing.
### - Training set: what the model learns from
### - Test set: what we use to evaluate the model
###   on data it has never seen before
### stratify=y ensures all 4 classes are proportionally
### represented in both the train and test sets.
### random_state=42 makes the split reproducible.

"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f"Training set size: {X_train.shape}")
print(f"Test set size:     {X_test.shape}")
print(f"\nClass distribution in training set:")
print(y_train.value_counts())
print(f"\nClass distribution in test set:")
print(y_test.value_counts())

"""## VERIFY STRATIFICATION
### We check that the class proportions are the same in both train and test sets. If stratification worked correctly, the percentages should be nearly identical in both sets.

"""

print("Class proportions in training set:")
print((y_train.value_counts() / len(y_train) * 100).round(2))

print("\nClass proportions in test set:")
print((y_test.value_counts() / len(y_test) * 100).round(2))

"""## TRAIN DECISION TREE (BASELINE)
### We train a Decision Tree using default hyperparameters. This gives us a baseline performance to compare against after we apply hyperparameter tuning later. Default settings mean the tree can grow as deep as it wants — which often leads to overfitting.

### BASELINE RESULTS — DECISION TREE (DEFAULT SETTINGS)

### Training Accuracy: 99.99%
### Test Accuracy:     83.58%

### This large gap (~16%) between training and test accuracy
### is a clear sign of OVERFITTING. The tree grew too deep
### and memorized the training data — including its noise —
### instead of learning general patterns.

### This is exactly why default settings are not enough.
### In the next steps we will apply hyperparameter tuning
### to control the tree depth and reduce overfitting,
### which should bring training and test accuracy closer
### together while improving test performance.
"""

from sklearn.tree import DecisionTreeClassifier

dt_baseline = DecisionTreeClassifier(random_state=42)
dt_baseline.fit(X_train, y_train)

print(f"Training Accuracy: {dt_baseline.score(X_train, y_train):.4f}")
print(f"Test Accuracy:     {dt_baseline.score(X_test, y_test):.4f}")

"""
## CLASSIFICATION REPORT
### Accuracy alone is not enough — especially with imbalanced
### classes. The classification report shows us:
### - Precision: of all predicted DEF, how many were correct?
### - Recall: of all actual DEF, how many did we catch?
### - F1-score: balance between precision and recall
### We check this for every class separately.
"""

from sklearn.metrics import classification_report

y_pred_dt = dt_baseline.predict(X_test)

print("Classification Report — Decision Tree Baseline")
print("=" * 55)
print(classification_report(y_test, y_pred_dt, target_names=['DEF', 'FWD', 'GK', 'MID']))

"""
## CONFUSION MATRIX
### A confusion matrix shows exactly where the model
### makes mistakes. Each row is the actual class,
### each column is the predicted class.
### The diagonal = correct predictions.
### Off-diagonal = mistakes (e.g. predicting MID as FWD).
"""

from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

cm = confusion_matrix(y_test, y_pred_dt, labels=['DEF', 'MID', 'FWD', 'GK'])
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['DEF', 'MID', 'FWD', 'GK'])

fig, ax = plt.subplots(figsize=(8, 6))
disp.plot(cmap='Blues', ax=ax)
plt.title('Confusion Matrix — Decision Tree Baseline')
plt.tight_layout()
plt.show()

"""## CHECK TREE DEPTH
### We check how deep the baseline tree grew.
### A very deep tree is a strong sign of overfitting —
### it memorized the training data instead of learning
### general patterns. This motivates our tuning in the
### next step where we will control max_depth.

### BASELINE ANALYSIS SUMMARY

### Tree depth: 26 | Leaves: 2019 → severe overfitting

### Best class:  GK  (F1 = 1.00) — unique stats, trivial to classify
### Worst class: MID (F1 = 0.71) — confused with both FWD and DEF

### Key confusion pairs:
### - MID ↔ FWD: 354 total mistakes (attacking mids play like forwards)
### - MID ↔ DEF: 274 total mistakes (defensive mids play like defenders)

### These confusions make football sense — the position boundaries
### are genuinely blurry for CAM, CDM type players.
### Tuning max_depth should reduce noise and improve MID/FWD scores.
"""

print(f"Baseline Decision Tree Depth: {dt_baseline.get_depth()}")
print(f"Number of leaves: {dt_baseline.get_n_leaves()}")

"""## DECISION TREE HYPERPARAMETER TUNING
### We use GridSearchCV to systematically test combinations
### of hyperparameters and find the best settings.
### GridSearchCV tries every combination and uses
### 5-fold cross validation to evaluate each one fairly.

### Parameters we are tuning:
### - max_depth: controls how deep the tree can grow
### - min_samples_split: min samples needed to split a node
### - min_samples_leaf: min samples required at a leaf node
### - criterion: the function used to measure split quality

"""

from sklearn.model_selection import GridSearchCV

param_grid_dt = {
    'max_depth': [3, 5, 10, 15, 20],
    'min_samples_split': [2, 10, 20, 50],
    'min_samples_leaf': [1, 5, 10, 20],
    'criterion': ['gini', 'entropy']
}

dt_grid = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid_dt,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

dt_grid.fit(X_train, y_train)

print(f"\nBest Parameters: {dt_grid.best_params_}")
print(f"Best Cross-Validation Accuracy: {dt_grid.best_score_:.4f}")

"""
## EVALUATE TUNED DECISION TREE
### We evaluate the best model found by GridSearchCV
### on the test set and compare it to our baseline.
### We expect the gap between train and test accuracy
### to be much smaller now — less overfitting.
"""

dt_best = dt_grid.best_estimator_

train_acc_tuned = dt_best.score(X_train, y_train)
test_acc_tuned  = dt_best.score(X_test, y_test)

print(f"Tuned Decision Tree")
print(f"{'='*40}")
print(f"Training Accuracy: {train_acc_tuned:.4f}")
print(f"Test Accuracy:     {test_acc_tuned:.4f}")
print(f"\nBaseline Comparison:")
print(f"Baseline Test Accuracy: 0.8358")
print(f"Tuned Test Accuracy:    {test_acc_tuned:.4f}")
print(f"Improvement:            {(test_acc_tuned - 0.8358):.4f}")

"""## TUNED DECISION TREE — CLASSIFICATION REPORT
### We generate a full classification report for the tuned
### model to see if per-class performance improved,
### especially for MID and FWD which struggled most
### in the baseline model.

"""

y_pred_dt_tuned = dt_best.predict(X_test)

print("Classification Report — Decision Tree Tuned")
print("=" * 55)
print(classification_report(y_test, y_pred_dt_tuned, target_names=['DEF', 'FWD', 'GK', 'MID']))

"""##TUNED DECISION TREE — CONFUSION MATRIX
### We plot the confusion matrix for the tuned model.
### Compare this to the baseline confusion matrix —
### we expect fewer mistakes between MID/FWD and MID/DEF.

"""

cm_tuned = confusion_matrix(y_test, y_pred_dt_tuned, labels=['DEF', 'MID', 'FWD', 'GK'])
disp_tuned = ConfusionMatrixDisplay(confusion_matrix=cm_tuned, display_labels=['DEF', 'MID', 'FWD', 'GK'])

fig, ax = plt.subplots(figsize=(8, 6))
disp_tuned.plot(cmap='Greens', ax=ax)
plt.title('Confusion Matrix — Decision Tree Tuned')
plt.tight_layout()
plt.show()

"""## EFFECT OF MAX_DEPTH ON ACCURACY
### We visualize how test accuracy changes as max_depth
### increases. This plot directly shows the overfitting
### point — where training accuracy keeps rising but
### test accuracy starts to plateau or drop.
### This is one of the most important plots in the report.

"""

depth_results = []

for depth in range(1, 26):
    dt_temp = DecisionTreeClassifier(max_depth=depth, random_state=42)
    dt_temp.fit(X_train, y_train)
    depth_results.append({
        'depth': depth,
        'train_acc': dt_temp.score(X_train, y_train),
        'test_acc': dt_temp.score(X_test, y_test)
    })

depth_df = pd.DataFrame(depth_results)

plt.figure(figsize=(10, 5))
plt.plot(depth_df['depth'], depth_df['train_acc'], label='Training Accuracy', marker='o')
plt.plot(depth_df['depth'], depth_df['test_acc'], label='Test Accuracy', marker='s')
plt.xlabel('Max Depth')
plt.ylabel('Accuracy')
plt.title('Decision Tree: Effect of Max Depth on Accuracy')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""### TUNING RESULTS SUMMARY — DECISION TREE
#
### Best parameters found by GridSearchCV:
### - criterion: entropy
### - max_depth: 10
### - min_samples_leaf: 5
### - min_samples_split: 50
#
### Results:
### - Test accuracy improved from 83.58% to 86.72% (+3.14%)
### - Train/test gap reduced from 16.41% to 1.37%
### - MID F1 improved from 0.71 to 0.77
### - FWD F1 improved from 0.76 to 0.81
#
### The max_depth plot clearly shows that depth=10 is the
### sweet spot — beyond that, training accuracy keeps rising
### but test accuracy plateaus, confirming overfitting.

## TRAIN RANDOM FOREST (BASELINE)
### We train a Random Forest using default hyperparameters.
### Default settings use 100 trees with no depth limit.
### Just like with the Decision Tree, we establish a
### baseline first before applying any tuning.
### We expect Random Forest to already outperform the
### baseline Decision Tree due to ensemble averaging.
"""

from sklearn.ensemble import RandomForestClassifier

rf_baseline = RandomForestClassifier(random_state=42, n_jobs=-1)
rf_baseline.fit(X_train, y_train)

print(f"Training Accuracy: {rf_baseline.score(X_train, y_train):.4f}")
print(f"Test Accuracy:     {rf_baseline.score(X_test, y_test):.4f}")

"""
#  RANDOM FOREST BASELINE — CLASSIFICATION REPORT
### We evaluate per-class performance for the baseline
### Random Forest and compare it directly to the
### Decision Tree baseline results.
"""

y_pred_rf = rf_baseline.predict(X_test)

print("Classification Report — Random Forest Baseline")
print("=" * 55)
print(classification_report(y_test, y_pred_rf, target_names=['DEF', 'FWD', 'GK', 'MID']))

"""
#  RANDOM FOREST BASELINE — CONFUSION MATRIX
### We plot the confusion matrix for the baseline
### Random Forest. Compare this to the Decision Tree
### confusion matrices to see if Random Forest makes
### fewer mistakes on the hard classes (MID and FWD).
"""

cm_rf = confusion_matrix(y_test, y_pred_rf, labels=['DEF', 'MID', 'FWD', 'GK'])
disp_rf = ConfusionMatrixDisplay(confusion_matrix=cm_rf, display_labels=['DEF', 'MID', 'FWD', 'GK'])

fig, ax = plt.subplots(figsize=(8, 6))
disp_rf.plot(cmap='Oranges', ax=ax)
plt.title('Confusion Matrix — Random Forest Baseline')
plt.tight_layout()
plt.show()

"""
#  EFFECT OF N_ESTIMATORS ON ACCURACY
### n_estimators controls how many trees are in the forest.
### We test a range of values to find where performance
### stabilizes — adding more trees beyond a certain point
### gives diminishing returns but increases training time.
"""

estimator_results = []

for n in [10, 20, 50, 100, 150, 200, 250, 300]:
    rf_temp = RandomForestClassifier(n_estimators=n, random_state=42, n_jobs=-1)
    rf_temp.fit(X_train, y_train)
    estimator_results.append({
        'n_estimators': n,
        'train_acc': rf_temp.score(X_train, y_train),
        'test_acc': rf_temp.score(X_test, y_test)
    })

est_df = pd.DataFrame(estimator_results)

plt.figure(figsize=(10, 5))
plt.plot(est_df['n_estimators'], est_df['train_acc'], label='Training Accuracy', marker='o')
plt.plot(est_df['n_estimators'], est_df['test_acc'], label='Test Accuracy', marker='s')
plt.xlabel('Number of Trees (n_estimators)')
plt.ylabel('Accuracy')
plt.title('Random Forest: Effect of n_estimators on Accuracy')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""# RANDOM FOREST HYPERPARAMETER TUNING
### We use GridSearchCV to find the best combination of:
### - n_estimators: number of trees in the forest
### - max_depth: maximum depth of each tree
### - max_features: number of features considered per split
### - min_samples_split: minimum samples to split a node
### Note: This will take longer than the Decision Tree
### tuning because each fit trains multiple trees.

"""

param_grid_rf = {
    'n_estimators': [50, 100, 200],
    'max_depth': [5, 10, 15, None],
    'max_features': ['sqrt', 'log2'],
    'min_samples_split': [2, 10, 20]
}

rf_grid = GridSearchCV(
    RandomForestClassifier(random_state=42, n_jobs=-1),
    param_grid_rf,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

rf_grid.fit(X_train, y_train)

print(f"\nBest Parameters: {rf_grid.best_params_}")
print(f"Best Cross-Validation Accuracy: {rf_grid.best_score_:.4f}")

"""
#  EVALUATE TUNED RANDOM FOREST
### We evaluate the best Random Forest found by GridSearchCV
### and compare it against:
### 1. Random Forest baseline
### 2. Tuned Decision Tree
### This is the core comparison of the entire project.
"""

rf_best = rf_grid.best_estimator_

train_acc_rf = rf_best.score(X_train, y_train)
test_acc_rf  = rf_best.score(X_test, y_test)

print(f"Tuned Random Forest")
print(f"{'='*40}")
print(f"Training Accuracy: {train_acc_rf:.4f}")
print(f"Test Accuracy:     {test_acc_rf:.4f}")
print(f"\nFull Comparison:")
print(f"{'Model':<30} {'Train Acc':>10} {'Test Acc':>10}")
print(f"{'-'*50}")
print(f"{'DT Baseline':<30} {'0.9999':>10} {'0.8358':>10}")
print(f"{'DT Tuned':<30} {'0.8809':>10} {'0.8672':>10}")
print(f"{'RF Baseline':<30} {rf_baseline.score(X_train, y_train):>10.4f} {rf_baseline.score(X_test, y_test):>10.4f}")
print(f"{'RF Tuned':<30} {train_acc_rf:>10.4f} {test_acc_rf:>10.4f}")

"""
# TUNED RANDOM FOREST — CLASSIFICATION REPORT
### Final per-class evaluation of the tuned Random Forest.
### We expect MID and FWD F1-scores to be higher than
### both Decision Tree versions due to ensemble averaging
### reducing variance on the hard boundary cases.
"""

y_pred_rf_tuned = rf_best.predict(X_test)

print("Classification Report — Random Forest Tuned")
print("=" * 55)
print(classification_report(y_test, y_pred_rf_tuned, target_names=['DEF', 'FWD', 'GK', 'MID']))

"""
#  TUNED RANDOM FOREST — CONFUSION MATRIX
### Final confusion matrix for the tuned Random Forest.
### This is the last of our four confusion matrices and
### should show the fewest mistakes overall.
"""

cm_rf_tuned = confusion_matrix(y_test, y_pred_rf_tuned, labels=['DEF', 'MID', 'FWD', 'GK'])
disp_rf_tuned = ConfusionMatrixDisplay(confusion_matrix=cm_rf_tuned, display_labels=['DEF', 'MID', 'FWD', 'GK'])

fig, ax = plt.subplots(figsize=(8, 6))
disp_rf_tuned.plot(cmap='Purples', ax=ax)
plt.title('Confusion Matrix — Random Forest Tuned')
plt.tight_layout()
plt.show()

"""# RANDOM FOREST TUNING RESULTS SUMMARY
#
### Best parameters found by GridSearchCV:
### - n_estimators: 200
### - max_depth: None (trees grow freely)
### - max_features: sqrt
### - min_samples_split: 20
#
### Results:
### - RF Tuned test accuracy: 88.62% (best overall)
### - Beats tuned DT by 1.90%
### - RF baseline (87.71%) already beats tuned DT (86.72%)
### - MID F1 improved from 0.71 (DT base) to 0.80 (RF tuned)
#
### The n_estimators plot shows accuracy stabilizes around
### 50-100 trees — beyond that, gains are minimal.
### RF still has a train/test gap (7.55%) because max_depth
### is unconstrained, but ensemble averaging keeps test
### performance strong despite individual trees overfitting.

# ACCURACY COMPARISON BAR CHART
### We plot training and test accuracy for all 4 models
### side by side. This is the main summary chart of the
### entire project — it shows at a glance which model
### performed best and how much each model overfits.
"""

models = ['DT Baseline', 'DT Tuned', 'RF Baseline', 'RF Tuned']
train_accs = [0.9999, 0.8809, 0.9999, 0.9217]
test_accs  = [0.8358, 0.8672, 0.8771, 0.8862]

x = np.arange(len(models))
width = 0.35

fig, ax = plt.subplots(figsize=(10, 6))
bars1 = ax.bar(x - width/2, train_accs, width, label='Training Accuracy', color='steelblue')
bars2 = ax.bar(x + width/2, test_accs,  width, label='Test Accuracy',     color='salmon')

ax.set_xlabel('Model')
ax.set_ylabel('Accuracy')
ax.set_title('Model Comparison: Training vs Test Accuracy')
ax.set_xticks(x)
ax.set_xticklabels(models)
ax.set_ylim(0.75, 1.05)
ax.legend()
ax.grid(axis='y', linestyle='--', alpha=0.7)

for bar in bars1:
    ax.annotate(f'{bar.get_height():.4f}',
                xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                xytext=(0, 3), textcoords='offset points', ha='center', fontsize=9)
for bar in bars2:
    ax.annotate(f'{bar.get_height():.4f}',
                xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                xytext=(0, 3), textcoords='offset points', ha='center', fontsize=9)

plt.tight_layout()
plt.show()

"""# F1-SCORE COMPARISON PER CLASS
### We compare F1-scores for each position class across
### all 4 models. This reveals which model handles the
### hard classes (MID, FWD) best, and confirms that
### improvements were consistent across all classes.

"""

f1_data = {
    'DEF': [0.91, 0.92, 0.93, 0.94],
    'FWD': [0.76, 0.81, 0.82, 0.83],
    'GK':  [1.00, 1.00, 1.00, 1.00],
    'MID': [0.71, 0.77, 0.78, 0.80]
}

x = np.arange(len(models))
width = 0.2
colors = ['steelblue', 'salmon', 'green', 'orange']

fig, ax = plt.subplots(figsize=(12, 6))

for i, (cls, scores) in enumerate(f1_data.items()):
    ax.bar(x + i * width, scores, width, label=cls, color=colors[i])

ax.set_xlabel('Model')
ax.set_ylabel('F1-Score')
ax.set_title('F1-Score per Class Across All Models')
ax.set_xticks(x + width * 1.5)
ax.set_xticklabels(models)
ax.set_ylim(0.6, 1.05)
ax.legend(title='Position Class')
ax.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""## OVERFITTING GAP COMPARISON
### We plot the gap between training and test accuracy
### for each model. A smaller gap means less overfitting.
### This chart directly shows how tuning and ensemble
### methods helped reduce overfitting in our models.

"""

gaps = [round(t - v, 4) for t, v in zip(train_accs, test_accs)]

fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.bar(models, gaps, color=['#d9534f','#5cb85c','#d9534f','#f0ad4e'])
ax.set_ylabel('Train - Test Accuracy Gap')
ax.set_title('Overfitting Gap per Model')
ax.set_ylim(0, 0.20)
ax.grid(axis='y', linestyle='--', alpha=0.7)

for bar in bars:
    ax.annotate(f'{bar.get_height():.4f}',
                xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                xytext=(0, 3), textcoords='offset points', ha='center', fontsize=10)

plt.tight_layout()
plt.show()

"""# FEATURE IMPORTANCE — RANDOM FOREST
### Random Forest can tell us which features it relied on
### most when making predictions. This is called feature
### importance. A higher value means the feature was more
### useful for splitting decisions across all trees.
### This adds depth to our analysis and helps explain
### why the model classifies positions the way it does.

"""

feature_names = ['pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic']
importances = rf_best.feature_importances_

feat_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances})
feat_df = feat_df.sort_values('Importance', ascending=True)

fig, ax = plt.subplots(figsize=(8, 5))
ax.barh(feat_df['Feature'], feat_df['Importance'], color='purple')
ax.set_xlabel('Importance Score')
ax.set_title('Feature Importance — Random Forest Tuned')
ax.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

print("\nFeature Importances:")
print(feat_df.sort_values('Importance', ascending=False).to_string(index=False))

"""# SIDE BY SIDE CONFUSION MATRICES
### We display the tuned Decision Tree and tuned Random
### Forest confusion matrices side by side for a direct
### visual comparison. This makes it easy to see exactly
### where each model makes mistakes and which one handles
### the hard boundary classes better.

"""

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

cm_dt = confusion_matrix(y_test, y_pred_dt_tuned, labels=['DEF', 'MID', 'FWD', 'GK'])
cm_rf = confusion_matrix(y_test, y_pred_rf_tuned, labels=['DEF', 'MID', 'FWD', 'GK'])

ConfusionMatrixDisplay(cm_dt, display_labels=['DEF', 'MID', 'FWD', 'GK']).plot(
    cmap='Greens', ax=axes[0])
axes[0].set_title('Decision Tree Tuned')

ConfusionMatrixDisplay(cm_rf, display_labels=['DEF', 'MID', 'FWD', 'GK']).plot(
    cmap='Purples', ax=axes[1])
axes[1].set_title('Random Forest Tuned')

plt.suptitle('Confusion Matrix Comparison: DT Tuned vs RF Tuned', fontsize=14)
plt.tight_layout()
plt.show()